# Generated by Django 3.0.3 on 2020-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=256)),
                ('ApiKey', models.CharField(max_length=256)),
                ('ApiSecretKey', models.CharField(max_length=256)),
                ('AccessToken', models.CharField(max_length=256)),
                ('AccessTokenSecret', models.CharField(max_length=256)),
            ],
        ),
    ]
