# Generated by Django 3.0.3 on 2020-04-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('tweets', models.CharField(max_length=512)),
                ('date_tweets', models.DateField()),
            ],
        ),
    ]
