# Generated by Django 3.0.3 on 2020-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='date_tweets',
            field=models.DateTimeField(max_length=256),
        ),
    ]
